server:
  port: 8761  # eureka server port number

spring:
  application:
    name: eurecaserver

# 유레카 서버는 유레카 클라이언트로 등록하지 않는다.
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
