server: #random port
  port: 8083
  servlet:
    context-path: /text

spring:
  application:
    name: text-service

  # Swagger 2.6.* 버전 이후 Path matching 에러 발생 - 해결법
  mvc:
    path match:
      matching-strategy: ant_path_matcher

  # mariadb database setting
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://k7c209.p.ssafy.io:3306/text?useSSL=false&serverTimezone=Asia/Seoul&useLegacyDatetimeCode=false&allowPublicKeyRetrieval=true
    username: dongsim
    password: dongsim12!

  # jpa setting
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

  devtools:
    livereload:
      enabled: true

# logging setting
logging:
  level:
    org:
      springframework:
        web: debug
    sql: debug

# Eureka client 등록 (Naming server에 service 등록) - 추후 microservices 연결 시 변경 필요
eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: false   # client 등록 시, true로 값 변경 필요
    fetch-registry: false         # client 등록 시, true로 값 변경 필요
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka   # eureka 서버 주소로 변경 필요

# application.yml 에 저장된 값을 읽어 REST API를 테스트하기 위한 dummy data
greeting:
  message: Welcome to the FairyTail!