spring.profiles.include: auth

server:
    port: 8000

eureka:
    client:
        register-with-eureka: true
        fetch-registry: true
        service-url:
            defaultZone: http://k7c209.p.ssafy.io:8761/eureka

spring:
    application:
        name: gateway-service

    cloud:
      gateway:
        routes:
            - id: img
              uri: lb://IMG
              predicates: # 전제 조건
                  - Path=/img/**
#              filters:
#                  - RewritePath=/user/(?<segment>.*), /$\{segment}


