spring.profiles.include: auth

server:
    port: 8000

eureka:
    client:
        register-with-eureka: true
        fetch-registry: true
        service-url:
            defaultZone: http://k7c209.p.ssafy.io:8761/eureka

spring:
    application:
        name: gateway-service

    cloud:
      gateway:
        routes:
            - id: img
              uri: lb://IMG
              predicates: # 전제 조건
                  - Path=/img/**
              filters:
#                - AuthorizationHeaderFilter

            - id: user
              uri: lb://USER
              predicates:
                  - Path=/user/**

            - id: video
              uri: lb://VIDEO
              predicates:
                  - Path=/video/**

            - id: audio
              uri: lb://AUDIO
              predicates:
                  - Path=/audio/**

            - id: text
              uri: lb://Text
              predicates:
                  - Path=/text/**
        #CORS
        globalcors:
          cors-configurations:
            '[/**]':
              allowed-origins: "*"
              allow-credentials: true
              allowed-headers:
                - x-requested-with
                - authorization
                - content-type
                - X-AUTH-TOKEN
                - X-CSRF-TOKEN
              allowed-methods:
                - POST
                - GET
                - PUT
                - OPTIONS
                - DELETE

