spring.profiles.include: auth

server:
    port: 8000

eureka:
    client:
        register-with-eureka: true
        fetch-registry: true
        service-url:
            defaultZone: http://k7c209.p.ssafy.io:8761/eureka

spring:
    application:
        name: gateway-service

    cloud:
      gateway:
        routes:
            - id: img
              uri: lb://IMG
              predicates: # 전제 조건
                  - Path=/img/**
              filters:
#                - AuthorizationHeaderFilter

            - id: user
              uri: lb://USER
              predicates:
                  - Path=/user/**

            - id: video
              uri: lb://VIDEO
              predicates:
                  - Path=/video/**

            - id: audio
              uri: lb://AUDIO
              predicates:
                  - Path=/audio/**

            - id: text
              uri: lb://Text
              predicates:
                  - Path=/text/**
        #CORS
        globalcors:
          cors-configurations:
            '[/**]':
              allowed-origins:
                - "https://k7c2091.p.ssafy.io"
                - "http://localhost:3000"
                - "https://k7c209.p.ssafy.io"
              allow-credentials: true
              allowed-headers: '*'
              exposed-headers: '*'
              allowed-methods:
                - POST
                - GET
                - PUT
                - DELETE
                - OPTIONS
        default-filters:
          - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials

