# Application Auth 와 관련한 인증 정보가 들어감

spring:
  security:
    oauth2:
      client:
        registration:
          google:
            # Todo: 인증 정보 - EC2 서버에 올린 후 변경 필요
            client-id: 587123311906-3en9j95qp639rr6p3d8fblpsgl3f6k7d.apps.googleusercontent.com
            client-secret: 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
            scope: profile, email

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://k7c209.p.ssafy.io:3306/user
    username: dongsim
    password: dongsim12!

  jpa:
    open-in-view: true
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

  devtools:
    livereload:
      enabled: true

# Token expiration 관련 설정
token:
  expiration_time: 86400000     # 토큰 유효기간 - 하루 (86400000 Milliseconds)
  secret: dongsimc209welovetoshareourballoonswithyou

